### PR TITLE
Import Translations

### PR DESCRIPTION
**Pull request by BrightspaceGitHubReader**

### CODE REVIEW

**Comment by omsmith** [comment]
@njostonehouse what's the deal with these? Crowding my PR list (could probably ignore the repo, but still curious)

**Comment by njostonehouse** [comment]
Definitely ignore this repo. It's for testing access to the GitHub APIs for Pull Requests from a tool for applying translations to FRA lang terms. Sorry for the spam!

**Comment by omsmith** [comment]
Could it also test closing the PR? :stuck_out_tongue:

**Comment by njostonehouse** [comment]
The tool isn't responsible for closing the PR, although I need to be more diligent in closing them myself. On it.

**Pull request closed without merging**
